version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    networks:
      - app_network
    env_file:
      - ./.env.prod
  db:
    container_name: pg_db
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    ports:
      - "5433:5433"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
volumes:
  db-data:
networks:
  app_network:
    external: true
